# Generated by Django 4.1 on 2023-05-10 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tconst', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titleType', models.CharField(max_length=20)),
                ('primaryTitle', models.CharField(max_length=255)),
                ('runtimeMinutes', models.IntegerField(null=True)),
                ('genres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.movie')),
                ('averageRating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('numVotes', models.IntegerField()),
            ],
        ),
    ]
